obj-m += switch_os.o

switch_os-y += module.o
switch_os-y += devices.o
switch_os-y += acpi.o
switch_os-y += configure_core_header.o
switch_os-y += suspend/hook_sleep_prepare.o

# Shipped core binary
switch_os-y += core.o

ccflags-y := -I $(ROOT_DIR)/shared/include -DMODULE

ifdef TRACE_DEBUG
	ccflags-y += -D TRACE_DEBUG
endif
