name: Build CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    container: alonlivne/switchos-build:latest
    env:
      GNU_EFI: /gnu-efi

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'
    - name: Build
      run: make build
